# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-e',
  'process.stdout.write(require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  ))', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'FitSync' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Bluetooth Low Energy
  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

  # Apple HealthKit
  pod 'RCTAppleHealthKit', :path => '../node_modules/react-native-health'

  # Permissions
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  # In-App Purchases (StoreKit)
  pod 'RNIap', :path => '../node_modules/react-native-iap'

  # Secure Keychain storage (membership state)
  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  # File system access (jailbreak detection)
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'FitSyncTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
